<?php

namespace AssoB2GBundle\Entity;

/**
 * LienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienRepository extends \Doctrine\ORM\EntityRepository
{
}
